Feature | Added dataUrl for Response
Sammyjo20/Saloon pull request #377
Opened 2024-02-23 08:22 UTC by guanguans

2024-02-25 14:04 UTC, Sammyjo20 commented
Hey, @guanguans thank you for submitting this PR - I think this is a cool addition to Saloon! I'm going to have a quick look over the PR but I think the implementation is solid.

2024-02-25 14:18 UTC, Sammyjo20 requested changes
Just one suggestion - would it be better to used the camel-case variant for `Content-Type`? I guess it's up to the PSR-7 implementation behind the scenes on how it handles it, but I'm pretty sure Guzzle normalises it anyway.

2024-02-25 14:18 UTC, Sammyjo20 commented on src/Http/Response.php
> +        return 'data:'.$this->psrResponse->getHeaderLine('content-type').';base64,'.base64_encode($this->body());
```suggestion
        return 'data:'.$this->psrResponse->getHeaderLine('Content-Type').';base64,'.base64_encode($this->body());
```

2024-02-26 03:29 UTC, guanguans commented on src/Http/Response.php
> +        return 'data:'.$this->psrResponse->getHeaderLine('content-type').';base64,'.base64_encode($this->body());
👍 It has been fixed.

2024-02-26 06:58 UTC, Sammyjo20 approved these changes
Looks good! I will release this later. Thanks again!

2024-02-27 19:57 UTC, merged