Add `Stringable` to OAuthConfig `set` methods.
Sammyjo20/Saloon pull request #429
Opened 2024-06-13 12:46 UTC by avenjamin

This PR adds `|Stringable` to the `set` methods in the OAuthConfig class that accept a string parameter.

In my use case, I'm constructing URLs using the [spatie/url](https://github.com/spatie/url) package and would like to be able to pass the URL directly to the `setAuthorizeEndpoint()` method:

```PHP
$this->oauthConfig()->setAuthorizeEndpoint(
    Url::fromString('https://api.example.com/oauth2/authorize')
    ->withQueryParameters([
        'app_key' => $appKey,
        'response_type' => 'code'
    ])
);
```

The `Url` implements the `Stringable` `__toString()` method so I can either cast to a string or update Saloon to support `Stringable` parameters :smile:

2024-06-14 21:03 UTC, juse-less requested changes
@avenjamin This would be a breaking change, but I'm not sure if this specific class can/should be seen as a public API.

Anything extending these methods will cause fatal errors as their definitions are now narrower.
I'm not sure how common it is to extend this class or override its methods, though.

If it's considered ok here, you still need to explicitly cast the value to a string, as strict types (which is used in this file) will prevent type juggling.

2024-06-14 21:03 UTC, juse-less commented on src/Helpers/OAuth2/OAuthConfig.php
>          $this->clientId = $clientId;
```suggestion
        $this->clientId = (string) $clientId;
```

2024-06-14 21:03 UTC, juse-less commented on src/Helpers/OAuth2/OAuthConfig.php
>          $this->clientSecret = $clientSecret;
```suggestion
        $this->clientSecret = (string) $clientSecret;
```

2024-06-14 21:03 UTC, juse-less commented on src/Helpers/OAuth2/OAuthConfig.php
>          $this->redirectUri = $redirectUri;
```suggestion
        $this->redirectUri = (string) $redirectUri;
```

2024-06-14 21:03 UTC, juse-less commented on src/Helpers/OAuth2/OAuthConfig.php
>          $this->authorizeEndpoint = $authorizeEndpoint;
```suggestion
        $this->authorizeEndpoint = (string) $authorizeEndpoint;
```

2024-06-14 21:03 UTC, juse-less commented on src/Helpers/OAuth2/OAuthConfig.php
>          $this->tokenEndpoint = $tokenEndpoint;
```suggestion
        $this->tokenEndpoint = (string) $tokenEndpoint;
```

2024-06-14 21:03 UTC, juse-less commented on src/Helpers/OAuth2/OAuthConfig.php
>          $this->userEndpoint = $userEndpoint;
```suggestion
        $this->userEndpoint = (string) $userEndpoint;
```

2024-08-03 13:52 UTC, Sammyjo20 commented
Thank you for the PR and the suggestions @juse-less. To be honest, I don't think Saloon should support casting strings like this, if I were to implement the PR, I would have to add it everywhere to keep it consistent.

2024-08-03 13:52 UTC, closed without merging