Feature | Added isJson and isXML functions to Response class
Sammyjo20/Saloon pull request #455
Opened 2024-09-12 13:46 UTC by mstfblci

Two new functions have been added to check if the response return is json or xml

2024-09-17 09:55 UTC, SRWieZ commented
This could be really useful; in a lot of my Connectors, I do things like this:

```php
public function hasRequestFailed(Response $response): ?bool
{
    // if psr response is json
    $contentType = $response->getPsrResponse()->getHeader('Content-Type');

    if (in_array('application/json', $contentType)) {
        return ! empty($response->json('errors'));
    }

    return null;
}
```

This PR would simplify it like this:
```php
public function hasRequestFailed(Response $response): ?bool
{
    if ($response->isJson()) {
        return ! empty($response->json('errors'));
    }

    return null;
}
```

I would argue, though, that I prefer a more strict comparison than `str_contains()` proposed in this PR.

2024-09-17 11:45 UTC, mstfblci commented
@SRWieZ Thank you for your support.

2024-12-03 00:32 UTC, Sammyjo20 requested changes
Love this! Super simple as well. Would you be able to write two tests for these functions just to prove coverage? Many thanks

2025-02-28 14:33 UTC, Sammyjo20 approved these changes

2025-02-28 14:36 UTC, Sammyjo20 commented
I'm going to have a Saloon day this weekend so I'll merge it then, thanks for the patience!

2025-03-01 10:52 UTC, SRWieZ commented
Glad to see you back! 

And thank you for all the work you put into Saloon.

2025-05-02 16:33 UTC, merged